### ISSUE TITLE
Re-add the refresh rate settings

### ISSUE THREAD

**Issue by colossatr0n** [SideQuestVR/SideQuest#105]
Can the refresh rate settings be added to future releases again? For Mac users, the only way to change the refresh rate on the Quest 2 is through SideQuest, since the Oculus app is only for Windows machines.

**Comment by DOSputin** [comment]
Wasn't the feature removed because recent Quest 2 updates have enabled 90hz as standard?
Or were you trying to reduce the refresh rate on your HMD back down to 72hz?

**Comment by colossatr0n** [comment]
The default on my quest was 72Hz. I checked by enabling the Oculus Developer Hub OVR Metrics Tool.

I know that "[all system software including Home, Guardian, and Passthrough will run at 90Hz by default](https://www.oculus.com/blog/the-first-gift-of-the-season-oculus-quest-update-adds-native-90hz-support-a-new-fitness-tracker-and-more/)" and that games will start shipping out at 90Hz native.

In a particular game, I get the best performance/quality with 72Hz at 2048 texture resolution. Allowing 90Hz at 2048 appears is a worse experience for the game I was playing, even though 90 Hz is supported for that game.

**Comment by DOSputin** [comment]
> The default on my quest was 72Hz. I checked by enabling the Oculus Developer Hub OVR Metrics Tool.

Just to for clarification,  Are you using a Quest V1 or V2?  
Also might be useful to post your current software revision info from the device info page.

> I know that "[all system software including Home, Guardian, and Passthrough will run at 90Hz by default](https://www.oculus.com/blog/the-first-gift-of-the-season-oculus-quest-update-adds-native-90hz-support-a-new-fitness-tracker-and-more/)" and that games will start shipping out at 90Hz native.

Yes.  This is why I presumed that the feature was removed from the Sidequest software.

> In a particular game, I get the best performance/quality with 72Hz at 2048 texture resolution. Allowing 90Hz at 2048 is a worse experience for the game I was playing, even though 90Hz is supported for that game.

Interesting.  Out of curiosity, —what game title was this?

> It would be nice to be able to reduce the refresh rate back to 72Hz to balance higher textures for games that ship natively with 90Hz.

**I agree with you.**  Just in the interest of being able to exert the maximum amount of control over the hardware, it seems like the feature should be re-implemented in future versions of the Sidequest software.

**Comment by sidequestlegend** [comment]
These will be added in a release going out today
