### ISSUE TITLE
Feature Request:  Controller Calibration or Reset

### ISSUE THREAD

**Issue by zachskaggs** [SideQuestVR/SideQuest#117]
There are many users with problems arising from calibration issues with the controllers, specifically the triggers (see this post: https://forums.oculusvr.com/t5/Oculus-Quest-2-and-Quest/Trigger-needs-calibration/td-p/860357)

I am one of these impacted users.  Oculus offered to RMA my controller, but since the bug appears software related, I'm pretty sure it would just happen again even with new controllers.  I can confirm that resetting the headset fixes this problem for some reason.

Is the controller calibration data stored in a place that can be easily reset and/or added as an advanced feature in SideQuest?  Something where we can just set the controllers in a specific orientation and click a button in SideQuest to have them recalibrate?

Thanks for your consideration.

**Comment by sidequestlegend** [comment]
I had a poke around and couldn't see anything. I'm afraid there is no such method as far as we are aware. Thanks for your input though!
