### ISSUE TITLE
Japanese Windows User (Double Byte) cannot evoke scrcpy

### ISSUE THREAD

**Issue by urashita** [SideQuestVR/SideQuest#126]
I am using SideQuest and scrcpy and found that I can not evoke scrcpy in some cases.

When I use single byte user (urashita) in Windows, SideQuest is installed here
C:\Users\urashita\AppData\Local\Programs\SideQuest

When I first launched SideQuest, scrcpy was downloaded and installed here
C:\Users\urashita\AppData\Roaming\SideQuest\scrcpy

Then I could always evoke scrcpy from SideQuest.

But when I use this user "1階のPC" in Windows, SideQuest is installed here
C:\Users\1階のPC\AppData\Local\Programs\SideQuest

When I first launched SideQuest, scrcpy was downloaded and installed here
C:\Users\1階のPC\AppData\Roaming\SideQuest\scrcpy

Then I could NEVER evoke scrcpy from SideQuest.

I think there may be a reason SideQuest cannot launch scrcpy.
The most possible cause is that scrcpyBinaryPath needs double quote?

I am reading SideQuest source code and skeptical around here.
SideQuest/desktop-app/src/app/app.service.ts
line 400: this.scrcpyBinaryPath = downloadPath;

I am willing to test and check it in my PC if there were a possible fixed code.

**Comment by sidequestlegend** [comment]
Hi there!

I got to testing this today and after I created and setup a new user on my PC with the name `1階の` I was indeed able to launch scrcpy without any problem. I am unsure of how else I can test this. Below was the scrcpy command that was output on the SideQuest console just before it opened. 

"C:\Users\1階の\AppData\Roaming\SideQuest\scrcpy\scrcpy.exe" --crop 1280:720:1500:350  -b 8000000  --max-fps 0  --max-size 0   -n --window-title "SideQuest Stream" -s 1WMHH814MP0383

And here is it working:

![image](https://user-images.githubusercontent.com/6830845/129202021-369b65f7-9805-4404-b90b-0998ca2b3740.png)

**Comment by urashita** [comment]
I said "1階のPC",  NOT "1階の".

**Comment by urashita** [comment]
What is going on about this issue?

**Comment by sidequestlegend** [comment]
Hi there, it seems to me the double byte characters are "1階の" and not "PC". I did test the double byte characters and it worked just fine. Im not sure what else you want me to do here.

**Comment by urashita** [comment]
Hi there, I tested as your advice and I got an interesting results.

1. SideQuest does not open mirroring window and I copy and pasted SideQuest's command into command prompt.

C:\Users\1階のPC>"C:\Users\1階のPC\AppData\Roaming\SideQuest\scrcpy\scrcpy.exe" --crop 1600:900:2017:510  -b 8000000  --max-fps 0  --max-size 0   -n --window-title "SideQuest Stream" -s 1WMHH842XM0492
INFO: scrcpy 1.11 <https://github.com/Genymobile/scrcpy>
adb: error: cannot stat '.\scrcpy-server': No such file or directory
ERROR: "adb push" returned with value 1
Press any key to continue...


2. Then I set SCRCPY_SERVER_PATH

C:\Users\1階のPC>set SCRCPY_SERVER_PATH=C:\Users\1階のPC\AppData\Roaming\SideQuest\scrcpy\scrcpy-server

C:\Users\1階のPC>"C:\Users\1階のPC\AppData\Roaming\SideQuest\scrcpy\scrcpy.exe" --crop 1600:900:2017:510  -b 8000000  --max-fps 0  --max-size 0   -n --window-title "SideQuest Stream" -s 1WMHH842XM0492
INFO: scrcpy 1.11 <https://github.com/Genymobile/scrcpy>
adb: error: cannot stat 'C:\Users\1�K��PC\AppData\Roaming\SideQuest\scrcpy\scrcpy-server': No such file or directory
ERROR: "adb push" returned with value 1
Press any key to continue...


3. Finally I set SCRCPY_SERVER_PATH from single byte path

C:\Users\1階のPC>set SCRCPY_SERVER_PATH=C:\Users\urashita\AppData\Roaming\SideQuest\scrcpy\scrcpy-server

C:\Users\1階のPC>"C:\Users\1階のPC\AppData\Roaming\SideQuest\scrcpy\scrcpy.exe" --crop 1600:900:2017:510  -b 8000000  --max-fps 0  --max-size 0   -n --window-title "SideQuest Stream" -s 1WMHH842XM0492
INFO: scrcpy 1.11 <https://github.com/Genymobile/scrcpy>
C:\Users\urashita\AppData\Roaming\SideQuest\scrcpy\scrcpy-server: 1 files pushed. 2.3 MB/s 
INFO: Initial texture: 1600x896

Then I got mirroring window.

I found that the problem is not SideQuest but scrcpy.
I will ask this issue to scrcpy project.
Thank you!

![commad1](https://user-images.githubusercontent.com/8746478/132283141-86ea06f8-aa88-4b17-9a31-24f46361db9c.png)

**Comment by urashita** [comment]
scrcpy project will fix soon.

https://github.com/Genymobile/scrcpy/issues/2619

**Comment by sidequestlegend** [comment]
Closing as scrcpy issue. Thank you.
