### ISSUE TITLE
File Browser: New / upload icons bottom right

### ISSUE THREAD

**Issue by RedBrumbler** [SideQuestVR/SideQuest#135]
The icons in the bottom right could be improved by giving them different icons

the "open download location" could be similiar to the one from a web browser

the "Create new folder" could be improved by having a plus icon on that folder instead of just being a folder icon

the "copy file" could be improved by adding an upload icon (arrow up?) to it
![image](https://user-images.githubusercontent.com/51795403/129205133-f3811246-3342-40b7-944e-f3308e0fa3d2.png)

**Comment by sidequestlegend** [comment]
> the "open download location" could be similiar to the one from a web browser
What does this look like? Got a screenshot?

**Comment by sidequestlegend** [comment]
Hows this:
![image](https://user-images.githubusercontent.com/6830845/129208089-63d00581-58e8-4b6e-9880-16ab2687bc95.png)

**Comment by sidequestlegend** [comment]
And when multiple items are selected:
![image](https://user-images.githubusercontent.com/6830845/129208200-1277b281-1db9-40bb-9c5d-00ba510e2446.png)

**Comment by sidequestlegend** [comment]
woops, closed by my commit message

**Comment by RedBrumbler** [comment]
not sure what the arrow in the box would do, but the rest seems more understandable ^_^

**Comment by RedBrumbler** [comment]
the arrow in the box does look a lot like the "pop out viewer" of video players online

**Comment by sidequestlegend** [comment]
Ok cool, lets go with this for now sure and see how we get on.
