### ISSUE TITLE
File Browser: dragging folders results in 2 deep folder with same name

### ISSUE THREAD

**Issue by RedBrumbler** [SideQuestVR/SideQuest#137]
Dropping in a folder makes the program create a folder in which it then drops that folder (so my files end up 2 folders deep)

![image](https://user-images.githubusercontent.com/51795403/129369465-deb761a3-2482-4aa0-b94c-d2d526a3eee4.png)

**Comment by hn3000** [comment]
Dropping multiple folders nests the second folder into the first. It looks like a combination of the existing behaviour that applied background jobs to the currently visible folder (drop a large folder, switch foreground folders and part of the large folder's content will end up in the new location) and a new behaviour that opens a newly uploaded folder.

**Comment by sidequestlegend** [comment]
This should have been resolved in the hotfix release - https://github.com/SideQuestVR/SideQuest/releases/tag/v0.10.24 let me know if it wasnt!

**Comment by hn3000** [comment]
Yes, it seems to work now.

Thanks!
