### ISSUE TITLE
Seg Fault/SIGSEGV when starting Linux Build 0.10.24

### ISSUE THREAD

**Issue by highb** [SideQuestVR/SideQuest#141]
I don't have a core dump, but I did verify that build 0.10.23 starts with no issue on my laptop running Ubuntu 20.04.1. If there are any additional details I can provide that would be useful, I'm happy to provide them.

**Comment by sidequestlegend** [comment]
Hmm the build runs fine in github actions, im not sure what could cause a seg fault but it could be electron-builder, or electron itself i guess.

**Comment by sidequestlegend** [comment]
Can you try this on v0.10.25+ ? A huge number of packages and internals have been updated.

**Comment by highb** [comment]
@sidequestlegend Hey sorry I missed your first message. I loaned my Quest out to a friend so I haven't been able to test it out. I'll try to repro this bug when I get it back.
