### ISSUE TITLE
Copying over ~70MB onto Quest 2 crashes SideQuest on macOS

### ISSUE THREAD

**Issue by hn3000** [SideQuestVR/SideQuest#142]
When copying folders with more than 70MB, SideQuest crashes with an exception in net.js

<img width="500" alt="Screenshot 2021-09-23 at 16 05 37" src="https://user-images.githubusercontent.com/133752/134524338-2987ed4b-3d4d-4ecd-a5cd-b9698edd98bf.png">

(Ok closes the box and SideQuest)

This happened after copying almost 70MB of data in 22 files in 11 folders ("33 items" as reported by macOS). Copying over a 100 files was no problem in another case where the files are about 600kb in size.

Looks similar to #73, reports a different error on a different line of net.js, though.

**Comment by sidequestlegend** [comment]
Hey there, this issue is actually caused by a poor connection over USB, often due to a problem with the cable or port. Thanks!

**Comment by hn3000** [comment]
I've tried different cables and can transfer the same folders over the same connection without moving anything when I use Android File Transfer. The underlying issue may be a problem in adb, though.
