### ISSUE TITLE
FileBrowser: Shortcut Icons

### ISSUE THREAD

**Issue by RedBrumbler** [SideQuestVR/SideQuest#144]
Allow the user to select a local image instead of pasting a URL, it's already possible by inputting a `file:///FILEPATH` uri, but this could be made more convenient by letting the user pick a file.

**Comment by bricefriha** [comment]
I can take a look at this @sidequestlegend 😉

**Comment by bricefriha** [comment]
Nevermind, it feels like this needs to get changed on the Website 😥

**Comment by sidequestlegend** [comment]
on it

**Comment by sidequestlegend** [comment]
added! it will be in the next release.
