### ISSUE TITLE
Move all "overwriting custom home environments" to a separate category.

### ISSUE THREAD

**Issue by unbelievableflavour** [SideQuestVR/SideQuest#158]
Hi! Since update v35 we now have the option to ADD environments instead of overwriting them. It might be good to separate the updated homes from the "old overwriting homes". Any chance we could add a separate category for "overwriting homes" or something? 

I for one think one of the most awesome features in SideQuest is installing custom homes. And I know a lot of other users use it for this as well. We should make it as easy as possible for the user to find "new" homes instead of overwriting homes. If I can help with that with like adding a new category or something I would be happy to offer a PR. But all overwriting homes would also need to be migrated to that new category.

You can easily find the old categories by checking for multiple download links since all old home environments have at least 3 downloads. New one's dont.

**Comment by sidequestlegend** [comment]
Hey there!

Thanks for the interest! The custom homes guys are in the process of converting all the old homes to the new system as we speak. I think it makes sense to leave things as they are and allow for them to migrate things over, I'm sure it won't take much longer. 

Thanks

Shane

**Comment by unbelievableflavour** [comment]
I don't think that's possible since not all home environments are from "custom homes" user. But time will tell then!

**Comment by sidequestlegend** [comment]
I think we will push all custom home Devs to the new system and will likely disable any stragglers that are no longer updated. Most are from the custom homes guys though with only a handful submitted by others.
