### ISSUE TITLE
To re-enable the proximity sensor there are easier instructions. 

### ISSUE THREAD

**Issue by sidequestlegend** [SideQuestVR/SideQuest#167]
It's in Devices > Power Settings > Autowake. Turn this on.

**Comment by Timocop** [comment]
Maybe an On/Off options would be better than just "Disable".

Turn off sensor:
`shell am broadcast -a com.oculus.vrpowermanager.prox_close`

Turn on sensor:
`shell am broadcast -a com.oculus.vrpowermanager.automation_disable`

**Comment by sidequestlegend** [comment]
Do on/off options persist though? Does this disable the proximity sensor or just wake the screen for a moment? Ill try these out and see i guess. Is there a way to tell if it is currently on or off using this method?

Thank you.
