### ISSUE TITLE
Archlinux Error: Fontconfig

### ISSUE THREAD

**Issue by CommanderRedYT** [SideQuestVR/SideQuest#176]
When I start `sidequest`, I get the following output:

```
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
```
Does someone know how to fix that?

**Comment by sidequestlegend** [comment]
I'm sorry, I cannot reproduce this and I don't have capacity to keep testing.
