### ISSUE TITLE
Specify path to apk to install

### ISSUE THREAD

**Issue by TashaSkyUp** [SideQuestVR/SideQuest#177]
While running the mobile version there is no way to specify where an APK is located so as to install it. The dialogue and defaults to a download directory which is hidden somewhere in the phones file structure.

**Comment by TashaSkyUp** [comment]
If someone can point me to the correct files I may work on this myself.

**Comment by sidequestlegend** [comment]
I appreciate your input! Our mobile app is not open source and I'm afraid the ability to install arbitrary APK files was omitted from it on purpose in order to avoid the use of our app for piracy. You can use another app called bugjaeger though.
