### ISSUE TITLE
SideQuest crash + memory leak

### ISSUE THREAD

**Issue by sidequestlegend** [SideQuestVR/SideQuest#73]
![image](https://user-images.githubusercontent.com/6830845/83270807-e53d1600-a1c0-11ea-857a-31ea3c7ea822.png)
i was copying around 30gb of data, it doesn't cache the data during transfer does it?

**Comment by gerryhernandez** [comment]
Can we ask for more info? I’d like to know if this 30 gb happened to be comprised of thousands of small files, rather than just a few big ones. If so, I have a hunch.
