### ISSUE TITLE
Request: Add a 'Download on SideQuest' button to the Branding page

### ISSUE THREAD

**Issue by andrelevi** [SideQuestVR/SideQuest#75]
It would be great to have a call-to-action download button for SideQuest, like the [App Store and Play Store buttons](https://i.imgur.com/LnCTyrE.png), for when linking to our SideQuest app page.

**Comment by sidequestlegend** [comment]
Good idea! I'll get the designer on this!

**Comment by sidequestlegend** [comment]
done!
