### ISSUE TITLE
Don't close connections made outside of SideQuest

### ISSUE THREAD

**Issue by josephsmendoza** [SideQuestVR/SideQuest#77]
I connected my quest to scrcpy wirelessly and then opened SideQuest to update an app. After closing SideQuest, the adb connection was closed, and I had to start all over. Adb is used for many more things than sidequest, and as such should not live and die with SideQuest.

**Comment by sidequestlegend** [comment]
Hi there! I'm afraid the ADB bundled with sidequest needs to be killed in order to be able to do other operations like uninstall or troubleshooting without the ADB folder being in use. This is intended functionality and for most sidequest users ADB does not get used for other things.

**Comment by josephsmendoza** [comment]
For the users that this does affect, it is a big issue, since side quest can't be used without breaking adb functionality outside of it. Perhaps an "advanced mode" or "advanced options" could be added to allow those users to disable closing the adb server as needed.
