### ISSUE TITLE
Advanced Options

### ISSUE THREAD

**Issue by josephsmendoza** [SideQuestVR/SideQuest#78]
I propose an "Advanced Mode" / "Advanced Options" menu to allow experienced users to do things like manual input of the connection uri for adb over network (#72 ) or leaving the adb server running otside of SideQuest (#77). This menu could include a warning / agreement that no support is provided for advanced features, and something like "Don't touch this if you don't know what you're doing".

**Comment by sidequestlegend** [comment]
I dont think this affects enough users for it to warrant consideration.

**Comment by josephsmendoza** [comment]
Given that SideQuest is not a commercial product, I would think affected user base size would not be a factor to warrant consideration.

**Comment by sidequestlegend** [comment]
I don't think our status really matters, the benefit to the users is always the driver behind any decisions we make.

Feel free to make a fork and add the functionality for yourself, but we are not interested in maintaining it at this time and will not accept a PR on this repository. 

Have a great day!
