### ISSUE TITLE
Is it possible to make the top bar a solid colour as banners actually interfere with visibility of the buttons

### ISSUE THREAD

**Issue by lalavr** [SideQuestVR/SideQuest#82]
![image](https://user-images.githubusercontent.com/59968075/95766734-98f3fd80-0cab-11eb-8a97-6d2a573e948c.png)

**Comment by lalavr** [comment]
The developer has writing in the spot underneath Get SideQuest and Promote so it looks bad.

**Comment by gerryhernandez** [comment]
![image](https://user-images.githubusercontent.com/10967987/97068113-a0ac7f80-1592-11eb-8299-53d18c4b907d.png)
Here's a preview showing it 100% solid. Take a look and let me know if you'd like any adjustments. If you decide you like it, it's a super quick change. Just let me know. :)

**Comment by sidequestlegend** [comment]
This would have to implemented in the website itself, and I think we have since decided to keep this as it is. The designer has vetod the solid color in favour of the transparent background.
