### ISSUE TITLE
It is impossible to paste passwords from a password manager into the Sidequest desktop application on macOS

### ISSUE THREAD

**Issue by sidequestlegend** [SideQuestVR/SideQuest#84]
Hey there, guys and gals. It is impossible to paste passwords from a password manager into the Sidequest desktop application on macOS. It might also affect the Windows client, but I haven't had the chance to test it yet.

Being able to paste allows us to use password managers, which is best-practice for security purposes. By not allowing pasting, we must use memorized passwords, which is a security hazard.

I'm a developer and I'd be happy to help. Let's get this fixed!

**Comment by gerryhernandez** [comment]
I can throw together a PR after work today.

**Comment by gerryhernandez** [comment]
Hey, I did notice that the CI build failed on the Windows build. What happened there?
