### ISSUE TITLE
Default Texture Size "Default button" incorrect resolution on Oculus Quest 2

### ISSUE THREAD

**Issue by Elisedlund** [SideQuestVR/SideQuest#86]
I was expecting the default button change the setting back to default on oculus quest 2 but it seems that it set a lower value than what is actually default.
(restarting the headset resets the Default Texture Size to it defaults which for me increases the clarity compared to using the default button)

**Comment by AlexxSeven** [comment]
Can confirm this is still happening as of v0.10.18

Excuse the massive code block but formatting isn't my forte at 12am lol.

`(n()(),Hi(270,0,null,null,4,"div",[["class","waves-effect waves-light btn set-sso margin-bottom margin-right pink-button"]],null,[[null,"click"]],(function(n,t,e){var l=!0,r=n.component;return"click"===t&&(l=!1!==r.setSSO(r.SSO._1440)&&l),l}),null,null)),ar(512,null,ba,wa,[Ce,xe,oe,pe]),or(272,278528,null,0,_a,[ba],{klass:[0,"klass"],ngClass:[1,"ngClass"]},null),lo(273,{"button-dark-theme":0,"button-light-theme":1,"waves-dark":2,"waves-light":3}),(n()(),io(-1,null,["Default - Oculus Quest 2"]))`

see specifically, `(l=!1!==r.setSSO(r.SSO._1440)`

**Comment by sidequestlegend** [comment]
this will be fixed today
