### ISSUE TITLE
Need to rebuild mobile launcher to support Quest 2

### ISSUE THREAD

**Issue by lvonasek** [SideQuestVR/SideQuest#91]
![Screenshot_20201115_154606_com android chrome](https://user-images.githubusercontent.com/6472545/99230075-25d03080-27ef-11eb-86e1-a3d22828da9b.jpg)

https://github.com/SideQuestVR/SideQuestAppLauncher/pull/1

**Comment by fooozhe** [comment]
same situation

**Comment by lvonasek** [comment]
The fix is already merged into the launcher repository, it needs only to be published. I was considering to put APK somewhere but then I decide to not to do it.

**Comment by sidequestlegend** [comment]
Apologies this is my bad. I will build and publish this today.

**Comment by sidequestlegend** [comment]
This has been built and released, apologies again for the delay. If im blocking like this in future feel free to take any and all action to  either poke me to pick up the slack or to make the build yourself. @lvonasek, you have done more maintenance on this app than i have for several months, if you want to be added as a collaborator and/or take over the listing on SideQuest im cool with that. 

Thanks again and apologies for the delay once more .

**Comment by lvonasek** [comment]
Thank you @sidequestlegend, however I would like to not go deeper into the launcher development. I fixed this two issues because it was annoying to connect headset to computer every time I wanted to launch any SideQuest game.

I am working on a few big projects and I cannot afford to work on any project for free.

**Comment by sidequestlegend** [comment]
No problem! Your contribution is much appreciated.
