### ISSUE TITLE
Support multiple devices on ScrCpy

### ISSUE THREAD

**Issue by sidequestlegend** [SideQuestVR/SideQuest#95]
Hi,
There is a major annoying bug in sidequest. It is easily fixed, please fix this!
When using the built-in function (The little TV icon at the top menu), AFTER selecting the correct headset, Scrcpy does not connect.

The log shows the command being run:
ScrCpy Error: {"err":{"killed":false,"code":1,"signal":null,"cmd":"\"C:\\Users\\username\\AppData\\Roaming\\SideQuest\\scrcpy\\scrcpy.exe\" --crop 1600:900:2017:510  -b 8000000  --max-fps 60  --max-size 0   -n --window-title \"SideQuest Stream\""},"stderr":"INFO: scrcpy 1.11 <https://github.com/Genymobile/scrcpy>\r\nERROR: \"adb push\" returned with value 1\r\nPress any key to continue...\r\n","command":"\"C:\\Users\\username\\AppData\\Roaming\\SideQuest\\scrcpy\\scrcpy.exe\" --crop 1600:900:2017:510  -b 8000000  --max-fps 60  --max-size 0   -n --window-title \"SideQuest Stream\""}

THIS SHOWS that the correct headset is not selected from the list.
The headset is already selected from the Top-Left menu, and shows the device ID, so please pass this the same as other UI elements like FPS and bitrate.

THE FIX for this is to simply add the "-s <device>" flag as per the Scrcpy documentation.

To be clear:

THIS DOES NOT WORK:
C:\\Users\\username\\AppData\\Roaming\\SideQuest\\scrcpy\\scrcpy.exe\" --crop 1600:900:2017:510  -b 8000000  --max-fps 60  --max-size 0   -n --window-title \"SideQuest Stream\"

THIS WORKS:
C:\\Users\\username\\AppData\\Roaming\\SideQuest\\scrcpy\\scrcpy.exe\" --crop 1600:900:2017:510  -b 8000000  --max-fps 60  --max-size 0   -n --window-title \"SideQuest Stream\" -s <device>

**Comment by KptnKMan** [comment]
Hi Shane, thanks for opening this issue.
I'm the same guy who raised the original request. 👋

**Comment by KptnKMan** [comment]
@sidequestlegend as an edit, it is worth noting that the last line of your post seems to be truncated or something.

It should read:

THIS DOES NOT WORK:
C:\Users\username\AppData\Roaming\SideQuest\scrcpy\scrcpy.exe" --crop 1600:900:2017:510 -b 8000000 --max-fps 60 --max-size 0 -n --window-title "SideQuest Stream"

THIS WORKS:
C:\Users\username\AppData\Roaming\SideQuest\scrcpy\scrcpy.exe" --crop 1600:900:2017:510 -b 8000000 --max-fps 60 --max-size 0 -n --window-title "SideQuest Stream" -s **<device_id>**

...with device ID being the ID from the `adb devices` command, or IP, such as:
```
PS C:\Users\karee> adb devices                                                                                                                                                                                                         List of devices attached
**1THSI9AJTB9552**  device
**1YODW9AJTB2945**  device
**192.168.1.28:5555**    device
**192.168.1.29:5555**    device
```

**Comment by sidequestlegend** [comment]
Sorry for the extended delay on this! This will be in the release today ( 0.10.21 ).
