### ISSUE TITLE
Download improvement

### ISSUE THREAD

**Issue by steevenlee** [SideQuestVR/SideQuest#96]
due to my poor network environment, never download  a game successfully,  some suggestions:
1 new pause/continue button 
2 auto retry on download broken
3 allow local apk install while downloading
4 show file size
5 show URL so I could download with 3rd party tool or find local fast mirror

**Comment by sidequestlegend** [comment]
Hi there! Im afraid for a number of reasons we cannot accommodate these.
1 new pause/continue button - This requires a server that supports resumable downloads. ALl our downloads come from different locations that our vendors supply so as such we don't have any control over this. 
2 auto retry on download broken - There is already a retry button for failed downloads. 
3 allow local apk install while downloading - This would greatly complicate things and does not help your problem of a poor internet connection.
4 show file size - as we dont host the files we dont always have access to this
5 show URL so I could download with 3rd party tool or find local fast mirror - as a matter of policy we dont not publish download urls to protect our developers from bad actors.
