### ISSUE TITLE
Can't stream video to Windows 20H2 

### ISSUE THREAD

**Issue by xqrkushnir** [SideQuestVR/SideQuest#99]
Oculus Quest 1, Windows 20H2

After upgrading my Windows from version 1904 to 20H2 I can't stream video with scrcpy anymore. The weird part is, sometimes I do get a picture from my Quest but only for a few frames. 

Any suggestions? 20H2 Update is quite buggy overall.

**Comment by sidequestlegend** [comment]
Hi there! You may need to direct this query to the ScrCpy devs, or you can use https://oculus.com/casting
